### ISSUE TITLE
Results for FB15K-IMG

### ISSUE THREAD

**Issue by IceIce1ce** [zjunlp/MKGformer#21]
Hi authors, thanks for your paper as well as your code. However, when I download the entire dataset from your baidu network disk and run the MKG task with the script you provided, the results are almost always 0. I wonder if something is wrong here.

**Comment by flow3rdown** [comment]
Thanks for your attention! Please check the versions of your `pytorch_lightning` and `transformers` and make them consistent with `requirement.txt`.

**Comment by IceIce1ce** [comment]
Hi author, I tried to reinstall all packages which were provided in requirements.txt. However, all results are still the same when I run MKG task with pretrained mode. 
<img width="796" alt="Untitled" src="https://user-images.githubusercontent.com/51022367/204859348-985d5db2-6033-4c3f-b5ac-aeebd12e588f.png">

**Comment by flow3rdown** [comment]
Hi, [issues4](https://github.com/zjunlp/MKGformer/issues/4#issuecomment-1305190044) encountered a similar problem as you and found out that the reason is the inconsistent versions of packages. Could you please check again if the environment is consistent? We recommend `transformers==4.11.3`, `pytorch_lightning==1.3.1`, `torch==1.7.0` and `torchmetrics==0.7.3`. If the versions are consistent, you can test the models with our released [checkpoints](https://drive.google.com/drive/folders/1NsLA7mXaVnhlYNvzRDWIcBxq2CpKF_6m) and see if the results are normal.

**Comment by IceIce1ce** [comment]
Thank you for your support. However, I have reference to issue 4 and tried uninstalling and reinstalling all packages by version in requirements.txt, the result is still the same (I tried both python versions 3.6 and 3.7).

**Comment by flow3rdown** [comment]
Sorry for the bad results. Is the result normal if you use the [checkpoints](https://drive.google.com/drive/folders/1NsLA7mXaVnhlYNvzRDWIcBxq2CpKF_6m) we provide? If you exclude version issues, it may be the dataset or the pre-trained model problem？

**Comment by IceIce1ce** [comment]
I used your checkpoints and all results are normal. Therefore, I think the inconsistent version of packages is not the main problem here, it may come from the pre-trained model problem. Anyway, thank for your support.

**Comment by IceIce1ce** [comment]
If you have time, can you rerun your code to verify the main problem?

**Comment by IceIce1ce** [comment]
Sorry author, after reinstalling requirement.txt on colab, I was able to run the results correctly. I think the error may happen due to my server has a little different configuration compared to colab, I need to check again. Anyway, thank for your code.
